// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/admin/announcements": {
            "post": {
                "description": "管理员发布区域公告，状态默认为 pending",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin (Announcement)"
                ],
                "summary": "发布区域公告 (需审核)",
                "parameters": [
                    {
                        "description": "公告内容",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_controllers.CreateRegionalAnnouncementRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "提交成功，等待审核",
                        "schema": {
                            "$ref": "#/definitions/easyfind_pkg_response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/admin/claims/pending": {
            "get": {
                "description": "管理员获取所有待审核的认领申请",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin (Claim)"
                ],
                "summary": "管理员获取待审核认领",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "页码",
                        "name": "page_num",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "每页数量",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "获取成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/easyfind_pkg_response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object",
                                            "additionalProperties": true
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/v1/admin/claims/{id}/approve": {
            "put": {
                "description": "管理员通过认领申请",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin (Claim)"
                ],
                "summary": "通过认领申请",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "认领ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "操作成功",
                        "schema": {
                            "$ref": "#/definitions/easyfind_pkg_response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/admin/claims/{id}/reject": {
            "put": {
                "description": "管理员驳回认领申请",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin (Claim)"
                ],
                "summary": "驳回认领申请",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "认领ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "操作成功",
                        "schema": {
                            "$ref": "#/definitions/easyfind_pkg_response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/admin/items": {
            "get": {
                "description": "管理员获取所有物品列表，支持筛选",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin (Item)"
                ],
                "summary": "管理员获取物品列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "校区",
                        "name": "campus",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "分类",
                        "name": "category",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "物品类型 (1:Lost, 2:Found)",
                        "name": "lost_or_found",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "状态",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "页码",
                        "name": "page_num",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "每页数量",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "获取成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/easyfind_pkg_response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object",
                                            "additionalProperties": true
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/v1/admin/items/pending": {
            "get": {
                "description": "管理员获取所有待审核的物品列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin (Item)"
                ],
                "summary": "管理员获取待审核物品",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "物品类型 (1:Lost, 2:Found)",
                        "name": "lost_or_found",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "页码",
                        "name": "page_num",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "每页数量",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "获取成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/easyfind_pkg_response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object",
                                            "additionalProperties": true
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/v1/admin/items/{id}/approve": {
            "put": {
                "description": "管理员通过物品发布的审核",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin (Item)"
                ],
                "summary": "通过审核",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "物品ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "操作成功",
                        "schema": {
                            "$ref": "#/definitions/easyfind_pkg_response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/admin/items/{id}/archive": {
            "put": {
                "description": "管理员归档物品帖子",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin (Item)"
                ],
                "summary": "归档帖子",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "物品ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "处理方式",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_controllers.ArchiveRecordRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "归档成功",
                        "schema": {
                            "$ref": "#/definitions/easyfind_pkg_response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/admin/items/{id}/reject": {
            "put": {
                "description": "管理员驳回物品发布的审核，需提供理由",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin (Item)"
                ],
                "summary": "驳回审核",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "物品ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "驳回理由",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_controllers.RejectRecordRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "操作成功",
                        "schema": {
                            "$ref": "#/definitions/easyfind_pkg_response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/claims": {
            "post": {
                "description": "用户申请认领物品",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Claim (User)"
                ],
                "summary": "申请认领",
                "parameters": [
                    {
                        "description": "申请信息",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_controllers.CreatClaimRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "申请成功",
                        "schema": {
                            "$ref": "#/definitions/easyfind_pkg_response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/claims/{id}": {
            "get": {
                "description": "根据ID获取认领详情 (发布者和申请者可见)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Claim (User)"
                ],
                "summary": "获取认领详情",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "认领ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "获取成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/easyfind_pkg_response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/easyfind_internal_models.Claim"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/v1/claims/{id}/confirm": {
            "put": {
                "description": "确认认领，将物品状态标记为已找到 (仅发布者可用)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Claim (User)"
                ],
                "summary": "确认认领",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "认领ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "确认成功",
                        "schema": {
                            "$ref": "#/definitions/easyfind_pkg_response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/items": {
            "get": {
                "description": "获取失物招领列表 (区分 Lost/Found)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Item (Public)"
                ],
                "summary": "获取失物招领列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "校区",
                        "name": "campus",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "分类",
                        "name": "category",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "物品类型 (1:Lost, 2:Found)",
                        "name": "lost_or_found",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "地点 (模糊搜索)",
                        "name": "location",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "最近几天 (例如 3 表示最近3天)",
                        "name": "days",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "状态 (默认 approved)",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "是否有悬赏 (true/false)",
                        "name": "has_bounty",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "页码",
                        "name": "page_num",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "每页数量",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "获取成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/easyfind_pkg_response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object",
                                            "additionalProperties": true
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "post": {
                "description": "用户发布失物或招领信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Item (User)"
                ],
                "summary": "发布失物招领",
                "parameters": [
                    {
                        "description": "发布信息",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_controllers.CreateRecordRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "发布成功",
                        "schema": {
                            "$ref": "#/definitions/easyfind_pkg_response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/items/all": {
            "get": {
                "description": "获取所有物品列表 (不区分 Lost/Found)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Item (Public)"
                ],
                "summary": "获取所有物品列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "校区",
                        "name": "campus",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "分类",
                        "name": "category",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "地点 (模糊搜索)",
                        "name": "location",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "最近几天 (例如 3 表示最近3天)",
                        "name": "days",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "状态 (默认 approved)",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "是否有悬赏 (true/false)",
                        "name": "has_bounty",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "页码",
                        "name": "page_num",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "每页数量",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "获取成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/easyfind_pkg_response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object",
                                            "additionalProperties": true
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/v1/items/{id}": {
            "get": {
                "description": "根据ID获取物品详情",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Item (Public)"
                ],
                "summary": "获取物品详情",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "物品ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "获取成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/easyfind_pkg_response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/easyfind_internal_models.Item"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "put": {
                "description": "用户更新自己发布的记录",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Item (User)"
                ],
                "summary": "更新记录",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "物品ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "更新信息",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_controllers.UpdateRecordRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "更新成功",
                        "schema": {
                            "$ref": "#/definitions/easyfind_pkg_response.Response"
                        }
                    }
                }
            },
            "delete": {
                "description": "用户删除自己发布的记录",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Item (User)"
                ],
                "summary": "删除记录",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "物品ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "删除成功",
                        "schema": {
                            "$ref": "#/definitions/easyfind_pkg_response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/items/{id}/cancel": {
            "put": {
                "description": "用户取消自己发布的记录 (通常用于已找到或不再需要)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Item (User)"
                ],
                "summary": "取消发布",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "物品ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "取消成功",
                        "schema": {
                            "$ref": "#/definitions/easyfind_pkg_response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/kinds": {
            "get": {
                "description": "获取所有物品分类",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Item (Public)"
                ],
                "summary": "获取分类列表",
                "responses": {
                    "200": {
                        "description": "获取成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/easyfind_pkg_response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "type": "string"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/v1/login": {
            "post": {
                "description": "用户登录接口，支持学生/老师、失物招领管理员、系统管理员",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "用户登录",
                "parameters": [
                    {
                        "description": "登录请求参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_controllers.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "认证失败",
                        "schema": {
                            "$ref": "#/definitions/easyfind_pkg_response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/logout": {
            "post": {
                "description": "退出登录，客户端需自行丢弃 Token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "退出登录",
                "responses": {
                    "200": {
                        "description": "退出成功",
                        "schema": {
                            "$ref": "#/definitions/easyfind_pkg_response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/my/claims": {
            "get": {
                "description": "获取当前用户的所有认领申请",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Claim (User)"
                ],
                "summary": "获取我的认领列表",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "页码",
                        "name": "page_num",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "每页数量",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "获取成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/easyfind_pkg_response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object",
                                            "additionalProperties": true
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/v1/my/items": {
            "get": {
                "description": "获取当前用户发布的所有记录",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Item (User)"
                ],
                "summary": "获取我的发布",
                "parameters": [
                    {
                        "type": "string",
                        "description": "状态",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "页码",
                        "name": "page_num",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "每页数量",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "获取成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/easyfind_pkg_response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object",
                                            "additionalProperties": true
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/v1/register": {
            "post": {
                "description": "注册新账号，用于测试不同身份",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "注册账号 (测试用)",
                "parameters": [
                    {
                        "description": "注册请求参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_controllers.RegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "注册失败",
                        "schema": {
                            "$ref": "#/definitions/easyfind_pkg_response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/super/announcements": {
            "get": {
                "description": "获取系统公告列表 (支持筛选)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "SuperAdmin"
                ],
                "summary": "获取公告列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "类型 (global/region)",
                        "name": "type",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "状态 (published/pending/rejected)",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "区域",
                        "name": "region",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "页码",
                        "name": "page_num",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "每页数量",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "获取成功",
                        "schema": {
                            "$ref": "#/definitions/easyfind_pkg_response.Response"
                        }
                    }
                }
            },
            "post": {
                "description": "发布新的系统公告",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "SuperAdmin"
                ],
                "summary": "发布系统公告",
                "parameters": [
                    {
                        "description": "公告内容",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_controllers.CreateAnnouncementRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "发布成功",
                        "schema": {
                            "$ref": "#/definitions/easyfind_pkg_response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/super/announcements/review": {
            "put": {
                "description": "审核区域公告 (通过/拒绝)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "SuperAdmin"
                ],
                "summary": "审核公告",
                "parameters": [
                    {
                        "description": "审核信息",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_controllers.ReviewAnnouncementRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "操作成功",
                        "schema": {
                            "$ref": "#/definitions/easyfind_pkg_response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/super/announcements/{id}": {
            "delete": {
                "description": "删除指定的公告",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "SuperAdmin"
                ],
                "summary": "删除公告",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "公告ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "删除成功",
                        "schema": {
                            "$ref": "#/definitions/easyfind_pkg_response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/super/categories": {
            "post": {
                "description": "添加新的物品分类",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "SuperAdmin"
                ],
                "summary": "添加物品分类",
                "parameters": [
                    {
                        "description": "分类信息",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_controllers.AddCategoryRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "添加成功",
                        "schema": {
                            "$ref": "#/definitions/easyfind_pkg_response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/super/categories/{id}": {
            "delete": {
                "description": "删除指定的物品分类",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "SuperAdmin"
                ],
                "summary": "删除物品分类",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "分类ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "删除成功",
                        "schema": {
                            "$ref": "#/definitions/easyfind_pkg_response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/super/data/cleanup": {
            "post": {
                "description": "清理指定天数前的无效数据(如已取消的帖子)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "SuperAdmin"
                ],
                "summary": "清理过期数据",
                "parameters": [
                    {
                        "description": "清理参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_controllers.CleanupRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "清理成功",
                        "schema": {
                            "$ref": "#/definitions/easyfind_pkg_response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/super/feedbacks": {
            "get": {
                "description": "获取用户提交的反馈与投诉",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "SuperAdmin"
                ],
                "summary": "获取用户反馈",
                "parameters": [
                    {
                        "type": "string",
                        "description": "状态 (pending, resolved)",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "页码",
                        "name": "page_num",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "每页数量",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "获取成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/easyfind_pkg_response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object",
                                            "additionalProperties": true
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/v1/super/feedbacks/{id}/reply": {
            "put": {
                "description": "管理员回复并处理反馈",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "SuperAdmin"
                ],
                "summary": "回复反馈",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "反馈ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "回复内容",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_controllers.ReplyFeedbackRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "操作成功",
                        "schema": {
                            "$ref": "#/definitions/easyfind_pkg_response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/super/stats": {
            "get": {
                "description": "超级管理员获取全局统计数据",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "SuperAdmin"
                ],
                "summary": "获取系统统计数据",
                "responses": {
                    "200": {
                        "description": "获取成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/easyfind_pkg_response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/easyfind_internal_models.SystemStats"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/v1/super/users": {
            "get": {
                "description": "获取所有用户列表 (支持按角色筛选)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "SuperAdmin"
                ],
                "summary": "获取用户列表",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "角色 (1:用户, 2:管理员)",
                        "name": "role",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "关键词 (用户名/姓名/昵称)",
                        "name": "keyword",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "页码",
                        "name": "page_num",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "每页数量",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "获取成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/easyfind_pkg_response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object",
                                            "additionalProperties": true
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/v1/super/users/admin": {
            "post": {
                "description": "创建新的失物招领管理员账号",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "SuperAdmin"
                ],
                "summary": "创建失物招领管理员",
                "parameters": [
                    {
                        "description": "管理员信息",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_controllers.CreateAdminRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "创建成功",
                        "schema": {
                            "$ref": "#/definitions/easyfind_pkg_response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/super/users/{id}/status": {
            "put": {
                "description": "修改账号激活状态",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "SuperAdmin"
                ],
                "summary": "禁用/启用账号",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "用户ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "状态",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_controllers.UpdateUserStatusRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "操作成功",
                        "schema": {
                            "$ref": "#/definitions/easyfind_pkg_response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/upload/image": {
            "post": {
                "description": "上传图片文件，支持自动去重，返回图片 URL",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Upload"
                ],
                "summary": "上传图片",
                "parameters": [
                    {
                        "type": "file",
                        "description": "图片文件",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "失败",
                        "schema": {
                            "$ref": "#/definitions/easyfind_pkg_response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/user/account": {
            "delete": {
                "description": "硬删除账号。普通用户只能注销自己，管理员/系统管理员可以注销任意账号。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "注销/删除账号 (硬删除)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "目标用户名 (管理员使用)",
                        "name": "username",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "注销成功",
                        "schema": {
                            "$ref": "#/definitions/easyfind_pkg_response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/user/password": {
            "put": {
                "description": "修改当前登录用户的密码",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "修改密码",
                "parameters": [
                    {
                        "description": "修改密码参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_controllers.UpdatePasswordRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "修改失败",
                        "schema": {
                            "$ref": "#/definitions/easyfind_pkg_response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/user/profile": {
            "get": {
                "description": "根据 Username 获取用户资料",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "获取个人资料",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户名",
                        "name": "username",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "获取成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/easyfind_pkg_response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/easyfind_internal_models.Account"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "put": {
                "description": "修改当前登录用户的资料，为空的字段不修改",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "修改个人资料",
                "parameters": [
                    {
                        "description": "需要修改的参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_controllers.UpdateProfileRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "修改成功",
                        "schema": {
                            "$ref": "#/definitions/easyfind_pkg_response.Response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "easyfind_internal_models.Account": {
            "type": "object",
            "properties": {
                "avatar": {
                    "description": "头像",
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "deletedAt": {
                    "$ref": "#/definitions/gorm.DeletedAt"
                },
                "first_login": {
                    "description": "是否首次登录",
                    "type": "boolean"
                },
                "id": {
                    "type": "integer"
                },
                "is_active": {
                    "description": "账号是否被封号（被管理员拿下）",
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "nickname": {
                    "description": "昵称",
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "role": {
                    "description": "1:学生/老师, 2:失物招领管理员, 3:系统管理员",
                    "allOf": [
                        {
                            "$ref": "#/definitions/easyfind_internal_models.UserRole"
                        }
                    ]
                },
                "updatedAt": {
                    "type": "string"
                },
                "username": {
                    "description": "学号或工号",
                    "type": "string"
                }
            }
        },
        "easyfind_internal_models.Claim": {
            "type": "object",
            "properties": {
                "claimant": {
                    "$ref": "#/definitions/easyfind_internal_models.Account"
                },
                "claimant_id": {
                    "type": "integer"
                },
                "createdAt": {
                    "type": "string"
                },
                "deletedAt": {
                    "$ref": "#/definitions/gorm.DeletedAt"
                },
                "id": {
                    "type": "integer"
                },
                "item": {
                    "$ref": "#/definitions/easyfind_internal_models.Item"
                },
                "item_id": {
                    "type": "integer"
                },
                "proof": {
                    "description": "证明材料 (如图片URL)",
                    "type": "string"
                },
                "status": {
                    "description": "状态: pending/approved/rejected/archived",
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "easyfind_internal_models.Item": {
            "type": "object",
            "properties": {
                "bounty": {
                    "description": "悬赏金额 (0表示无悬赏)",
                    "type": "number"
                },
                "campus": {
                    "description": "类型 (lost: 失物, found: 招领)",
                    "type": "string"
                },
                "category": {
                    "description": "分类",
                    "type": "string"
                },
                "contact_name": {
                    "description": "联系人姓名",
                    "type": "string"
                },
                "contact_phone": {
                    "description": "联系人电话",
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "deletedAt": {
                    "$ref": "#/definitions/gorm.DeletedAt"
                },
                "description": {
                    "description": "描述",
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "img1": {
                    "description": "照片 (JSON或逗号分隔的URL)",
                    "type": "string"
                },
                "img2": {
                    "description": "照片 (JSON或逗号分隔的URL)",
                    "type": "string"
                },
                "img3": {
                    "description": "照片 (JSON或逗号分隔的URL)",
                    "type": "string"
                },
                "img4": {
                    "type": "string"
                },
                "location": {
                    "description": "地点",
                    "type": "string"
                },
                "process_method": {
                    "description": "处理方式",
                    "type": "string"
                },
                "publisher": {
                    "description": "发布者信息",
                    "allOf": [
                        {
                            "$ref": "#/definitions/easyfind_internal_models.Account"
                        }
                    ]
                },
                "publisher_id": {
                    "type": "integer"
                },
                "reject_reason": {
                    "description": "审核拒绝原因",
                    "type": "string"
                },
                "reviewer": {
                    "description": "审核者信息",
                    "allOf": [
                        {
                            "$ref": "#/definitions/easyfind_internal_models.Account"
                        }
                    ]
                },
                "reviewer_id": {
                    "type": "integer"
                },
                "status": {
                    "description": "状态",
                    "allOf": [
                        {
                            "$ref": "#/definitions/easyfind_internal_models.ItemStatus"
                        }
                    ]
                },
                "time": {
                    "description": "时间",
                    "type": "string"
                },
                "title": {
                    "description": "标题",
                    "type": "string"
                },
                "type": {
                    "$ref": "#/definitions/easyfind_internal_models.ItemType"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "easyfind_internal_models.ItemStatus": {
            "type": "string",
            "enum": [
                "pending",
                "approved",
                "matched",
                "claimed",
                "rejected",
                "cancelled",
                "archived"
            ],
            "x-enum-comments": {
                "StatusApproved": "已通过",
                "StatusArchived": "已归档（认领成功或者超时未认领）",
                "StatusCancelled": "已取消",
                "StatusClaimed": "已认领（确认是对的人）",
                "StatusMatched": "已匹配（找到对应的人来对话了）",
                "StatusPending": "待审核",
                "StatusRejected": "已驳回"
            },
            "x-enum-descriptions": [
                "待审核",
                "已通过",
                "已匹配（找到对应的人来对话了）",
                "已认领（确认是对的人）",
                "已驳回",
                "已取消",
                "已归档（认领成功或者超时未认领）"
            ],
            "x-enum-varnames": [
                "StatusPending",
                "StatusApproved",
                "StatusMatched",
                "StatusClaimed",
                "StatusRejected",
                "StatusCancelled",
                "StatusArchived"
            ]
        },
        "easyfind_internal_models.ItemType": {
            "type": "string",
            "enum": [
                "lost",
                "found"
            ],
            "x-enum-varnames": [
                "TypeLost",
                "TypeFound"
            ]
        },
        "easyfind_internal_models.SystemStats": {
            "type": "object",
            "properties": {
                "active_users": {
                    "description": "30天内活跃",
                    "type": "integer"
                },
                "solved_items": {
                    "description": "status = claimed/matched",
                    "type": "integer"
                },
                "today_items": {
                    "type": "integer"
                },
                "total_claims": {
                    "type": "integer"
                },
                "total_items": {
                    "type": "integer"
                },
                "total_users": {
                    "type": "integer"
                }
            }
        },
        "easyfind_internal_models.UserRole": {
            "type": "integer",
            "enum": [
                1,
                2,
                3
            ],
            "x-enum-varnames": [
                "RoleStudentTeacher",
                "RoleLFAdmin",
                "RoleSysAdmin"
            ]
        },
        "easyfind_pkg_response.Response": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "description": "使用 data 统一包裹数据"
                },
                "msg": {
                    "type": "string"
                }
            }
        },
        "gorm.DeletedAt": {
            "type": "object",
            "properties": {
                "time": {
                    "type": "string"
                },
                "valid": {
                    "description": "Valid is true if Time is not NULL",
                    "type": "boolean"
                }
            }
        },
        "internal_controllers.AddCategoryRequest": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "name": {
                    "type": "string"
                }
            }
        },
        "internal_controllers.ArchiveRecordRequest": {
            "type": "object",
            "required": [
                "process_method"
            ],
            "properties": {
                "process_method": {
                    "type": "string"
                }
            }
        },
        "internal_controllers.CleanupRequest": {
            "type": "object",
            "required": [
                "days"
            ],
            "properties": {
                "days": {
                    "type": "integer",
                    "minimum": 1
                }
            }
        },
        "internal_controllers.CreatClaimRequest": {
            "type": "object",
            "required": [
                "item_id"
            ],
            "properties": {
                "item_id": {
                    "type": "integer"
                },
                "proof": {
                    "type": "string"
                }
            }
        },
        "internal_controllers.CreateAdminRequest": {
            "type": "object",
            "required": [
                "name",
                "password",
                "username"
            ],
            "properties": {
                "name": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "internal_controllers.CreateAnnouncementRequest": {
            "type": "object",
            "required": [
                "content",
                "title"
            ],
            "properties": {
                "content": {
                    "type": "string"
                },
                "is_top": {
                    "type": "boolean"
                },
                "region": {
                    "description": "if type is region",
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "type": {
                    "description": "global or region",
                    "type": "string"
                }
            }
        },
        "internal_controllers.CreateRecordRequest": {
            "type": "object",
            "required": [
                "title",
                "type"
            ],
            "properties": {
                "bounty": {
                    "type": "number"
                },
                "campus": {
                    "type": "string"
                },
                "category": {
                    "type": "string"
                },
                "contact_name": {
                    "type": "string"
                },
                "contact_phone": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "img1": {
                    "type": "string"
                },
                "img2": {
                    "type": "string"
                },
                "img3": {
                    "type": "string"
                },
                "img4": {
                    "type": "string"
                },
                "location": {
                    "type": "string"
                },
                "time": {
                    "description": "前端传字符串，后端解析",
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "type": {
                    "type": "string",
                    "enum": [
                        "lost",
                        "found"
                    ]
                }
            }
        },
        "internal_controllers.CreateRegionalAnnouncementRequest": {
            "type": "object",
            "required": [
                "content",
                "region",
                "title"
            ],
            "properties": {
                "content": {
                    "type": "string"
                },
                "is_top": {
                    "type": "boolean"
                },
                "region": {
                    "description": "Region is required for regional announcements",
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "internal_controllers.LoginRequest": {
            "type": "object",
            "required": [
                "password",
                "role",
                "username"
            ],
            "properties": {
                "password": {
                    "type": "string"
                },
                "remember": {
                    "description": "记住我",
                    "type": "boolean"
                },
                "role": {
                    "description": "1:学生/老师, 2:失物招领管理员, 3:系统管理员",
                    "type": "integer"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "internal_controllers.LoginResponse": {
            "type": "object",
            "properties": {
                "token": {
                    "type": "string"
                }
            }
        },
        "internal_controllers.RegisterRequest": {
            "type": "object",
            "required": [
                "password",
                "role",
                "username"
            ],
            "properties": {
                "name": {
                    "type": "string"
                },
                "nickname": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "role": {
                    "type": "integer"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "internal_controllers.RejectRecordRequest": {
            "type": "object",
            "required": [
                "reject_reason"
            ],
            "properties": {
                "reject_reason": {
                    "type": "string"
                }
            }
        },
        "internal_controllers.ReplyFeedbackRequest": {
            "type": "object",
            "required": [
                "reply"
            ],
            "properties": {
                "reply": {
                    "type": "string"
                }
            }
        },
        "internal_controllers.ReviewAnnouncementRequest": {
            "type": "object",
            "required": [
                "id",
                "status"
            ],
            "properties": {
                "id": {
                    "type": "integer"
                },
                "status": {
                    "description": "only allow these two",
                    "type": "string",
                    "enum": [
                        "published",
                        "rejected"
                    ]
                }
            }
        },
        "internal_controllers.UpdatePasswordRequest": {
            "type": "object",
            "required": [
                "new_password",
                "old_password"
            ],
            "properties": {
                "new_password": {
                    "type": "string"
                },
                "old_password": {
                    "type": "string"
                }
            }
        },
        "internal_controllers.UpdateProfileRequest": {
            "type": "object",
            "properties": {
                "avatar": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "nickname": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                }
            }
        },
        "internal_controllers.UpdateRecordRequest": {
            "type": "object",
            "properties": {
                "campus": {
                    "type": "string"
                },
                "category": {
                    "type": "string"
                },
                "contact_name": {
                    "type": "string"
                },
                "contact_phone": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "img1": {
                    "type": "string"
                },
                "img2": {
                    "type": "string"
                },
                "img3": {
                    "type": "string"
                },
                "img4": {
                    "type": "string"
                },
                "location": {
                    "type": "string"
                },
                "time": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "internal_controllers.UpdateUserStatusRequest": {
            "type": "object",
            "properties": {
                "is_active": {
                    "type": "boolean"
                }
            }
        },
        "internal_controllers.UploadResponse": {
            "type": "object",
            "properties": {
                "file_name": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "EasyFind API",
	Description:      "This is the API server for EasyFind application.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
